import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-secondary p-2 px-6 rounded-2xl m-6">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-mono">
              Meme
              <span className="font-mono px-1 inline-flex font-light">
                Annotation
              </span>
            </h1>
            <div className="flex items-center gap-4">
              <Link href="/" className="text-lg font-mono">
                Home
              </Link>
              <Link href="/annotate" className="text-lg font-mono">
                Annotate
              </Link>
            </div>
          </div>
        </nav>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
